-- Unit-conversion data on master_ingredients (reviewed/approved). See
-- unit_conversions_proposal.md. Additive: display computes conversions live.
alter table master_ingredients add column if not exists unit_type text;
alter table master_ingredients add column if not exists grams_per_cup numeric;
alter table master_ingredients add column if not exists conversion_is_approximate bool default false;

update master_ingredients set unit_type='solid_volume', grams_per_cup=125, conversion_is_approximate=true where canonical_name='All-purpose flour';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Almond milk';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Asafoetida';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Baby spinach';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Baking powder';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Banana';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Bay leaf';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Beef mince';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Beef stock';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Beef stock cube';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Beetroot powder';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Berries';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Black cardamom';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Black mustard seeds';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Black pepper';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Bottle gourd';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Bread';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Broccoli';
update master_ingredients set unit_type='solid_volume', grams_per_cup=200, conversion_is_approximate=true where canonical_name='Brown sugar';
update master_ingredients set unit_type='solid_volume', grams_per_cup=100, conversion_is_approximate=true where canonical_name='Buckwheat flakes';
update master_ingredients set unit_type='solid_volume', grams_per_cup=227, conversion_is_approximate=true where canonical_name='Butter';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cabbage';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Canned chopped tomatoes';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Canned diced tomatoes';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Carrot';
update master_ingredients set unit_type='solid_volume', grams_per_cup=130, conversion_is_approximate=true where canonical_name='Cashews';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cauliflower';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Celery';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chapati';
update master_ingredients set unit_type='solid_volume', grams_per_cup=113, conversion_is_approximate=true where canonical_name='Cheese';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chicken breast';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chicken leg';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chicken mince';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chicken thigh';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chicken tikka';
update master_ingredients set unit_type='solid_volume', grams_per_cup=164, conversion_is_approximate=true where canonical_name='Chickpeas';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chili powder';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Chinese cooking wine';
update master_ingredients set unit_type='solid_volume', grams_per_cup=170, conversion_is_approximate=true where canonical_name='Chocolate chips';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cider vinegar';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cinnamon';
update master_ingredients set unit_type='solid_volume', grams_per_cup=85, conversion_is_approximate=true where canonical_name='Cocoa powder';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Coconut oil';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cooking oil';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Coriander powder';
update master_ingredients set unit_type='solid_volume', grams_per_cup=28, conversion_is_approximate=true where canonical_name='Cornflakes';
update master_ingredients set unit_type='solid_volume', grams_per_cup=120, conversion_is_approximate=true where canonical_name='Cornstarch';
update master_ingredients set unit_type='solid_volume', grams_per_cup=226, conversion_is_approximate=true where canonical_name='Cottage cheese';
update master_ingredients set unit_type='solid_volume', grams_per_cup=232, conversion_is_approximate=true where canonical_name='Cream cheese';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Crushed red pepper flakes';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Crushed tomatoes';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Cumin seeds';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Curry leaves';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Curry sauce';
update master_ingredients set unit_type='solid_volume', grams_per_cup=240, conversion_is_approximate=true where canonical_name='Dijon mustard';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Dill';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Dried basil';
update master_ingredients set unit_type='solid_volume', grams_per_cup=185, conversion_is_approximate=true where canonical_name='Dried black-eyed peas';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Dried fenugreek leaves';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Dried oregano';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Dried red chile';
update master_ingredients set unit_type='solid_volume', grams_per_cup=185, conversion_is_approximate=true where canonical_name='Dried red kidney beans';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Egg';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fajita seasoning';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fire roasted tomatoes';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh basil';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh cilantro';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh coriander';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh fenugreek leaves';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh ginger';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Fresh parsley';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Garam masala';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Garlic';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Garlic powder';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Ghee';
update master_ingredients set unit_type='solid_volume', grams_per_cup=240, conversion_is_approximate=true where canonical_name='Ginger garlic paste';
update master_ingredients set unit_type='solid_volume', grams_per_cup=150, conversion_is_approximate=true where canonical_name='Goat''s cheese';
update master_ingredients set unit_type='solid_volume', grams_per_cup=200, conversion_is_approximate=true where canonical_name='Granulated sugar';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Green cardamom pods';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Green chile';
update master_ingredients set unit_type='solid_volume', grams_per_cup=200, conversion_is_approximate=true where canonical_name='Green lentils';
update master_ingredients set unit_type='solid_volume', grams_per_cup=145, conversion_is_approximate=true where canonical_name='Green peas';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Ground cumin';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Ground fennel seeds';
update master_ingredients set unit_type='solid_volume', grams_per_cup=149, conversion_is_approximate=true where canonical_name='Ground flaxseed';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Ground goat meat';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Ground green cardamom';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Half and half';
update master_ingredients set unit_type='solid_volume', grams_per_cup=180, conversion_is_approximate=true where canonical_name='Haricot beans';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Honey';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Italian herbs';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Lemon juice';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Lemon wedges';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Light cream';
update master_ingredients set unit_type='solid_volume', grams_per_cup=320, conversion_is_approximate=true where canonical_name='Mango chutney';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Maple syrup';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Medium curry powder';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Milk';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Mint sauce';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Mushroom ketchup';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Mustard oil';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Nigella seeds';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Nutmeg';
update master_ingredients set unit_type='solid_volume', grams_per_cup=92, conversion_is_approximate=true where canonical_name='Oat flour';
update master_ingredients set unit_type='solid_volume', grams_per_cup=90, conversion_is_approximate=true where canonical_name='Oats';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Olive oil';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Onion';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Onion powder';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Paneer';
update master_ingredients set unit_type='solid_volume', grams_per_cup=50, conversion_is_approximate=true where canonical_name='Panko breadcrumbs';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Paprika';
update master_ingredients set unit_type='solid_volume', grams_per_cup=100, conversion_is_approximate=true where canonical_name='Parmigiano-Reggiano cheese';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Pasta';
update master_ingredients set unit_type='solid_volume', grams_per_cup=258, conversion_is_approximate=true where canonical_name='Peanut butter';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Pepper (bell)';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Pizza dough';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Pizza sauce';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Potato';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Puff pastry';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Red onion';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Red-skinned potato';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Saffron';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Salt';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Sambar masala';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Sesame oil';
update master_ingredients set unit_type='solid_volume', grams_per_cup=144, conversion_is_approximate=true where canonical_name='Sesame seeds';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Shallot';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Shallot';
update master_ingredients set unit_type='solid_volume', grams_per_cup=113, conversion_is_approximate=true where canonical_name='Shredded mozzarella';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Soy sauce';
update master_ingredients set unit_type='solid_volume', grams_per_cup=200, conversion_is_approximate=true where canonical_name='Split pigeon peas';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Spring onion';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Steamed vegetables';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Stewing beef';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Sun-dried tomatoes';
update master_ingredients set unit_type='solid_volume', grams_per_cup=270, conversion_is_approximate=true where canonical_name='Tamarind paste';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Thick coconut milk';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Thyme';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Tomato';
update master_ingredients set unit_type='solid_volume', grams_per_cup=262, conversion_is_approximate=true where canonical_name='Tomato paste';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Tomato sauce';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Turmeric';
update master_ingredients set unit_type='weight_only', grams_per_cup=null, conversion_is_approximate=false where canonical_name='UNCLEAR';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Vanilla extract';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Vegetable stock';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Vinegar';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Water';
update master_ingredients set unit_type='solid_volume', grams_per_cup=180, conversion_is_approximate=true where canonical_name='White beans (cannellini)';
update master_ingredients set unit_type='count', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Whole cloves';
update master_ingredients set unit_type='solid_volume', grams_per_cup=120, conversion_is_approximate=true where canonical_name='Whole wheat flour';
update master_ingredients set unit_type='liquid_volume', grams_per_cup=null, conversion_is_approximate=false where canonical_name='Worcestershire sauce';
update master_ingredients set unit_type='solid_volume', grams_per_cup=207, conversion_is_approximate=true where canonical_name='Yellow moong beans';
update master_ingredients set unit_type='solid_volume', grams_per_cup=245, conversion_is_approximate=true where canonical_name='Yogurt';
