-- Master ingredients seed + back-link (Step 2). Generated from the reviewed/approved
-- proposal (master_ingredients_proposal.md). 153 canonical groups; existing name
-- fields untouched. Run once after 20260620_master_ingredients.sql.

insert into master_ingredients (canonical_name, default_category, aliases) values
  ('Chicken mince', 'fridge', array['/ 1 lb chicken mince','/ 500 g ground chicken  (Note 1)','1 pound/0.5kg ground chicken','CHICKEN MEATBALLS']::text[]),
  ('Cinnamon', 'pantry', array['0.5inch piece of cinnamon','cinnamon']::text[]),
  ('Canned diced tomatoes', 'pantry', array['1  can diced or whole peeled tomatoes','ounces  can diced tomatoes','canned diced tomato','diced tomatoes']::text[]),
  ('Bay leaf', 'pantry', array['1 bay leaf','3 bay leaves']::text[]),
  ('Beef stock cube', 'pantry', array['1 beef stock cube']::text[]),
  ('Black cardamom', 'pantry', array['1 black cardamom pod']::text[]),
  ('Cabbage', 'fridge', array['1 Cabbage','shredded and steamed Savoy cabbage']::text[]),
  ('Celery', 'fridge', array['1 celery stick','3 celery sticks']::text[]),
  ('Egg', 'fridge', array['1 egg','1 large egg','1.5-2 eggs','2 eggs','3-4 eggs','6 egg whites','8 eggs','Omelette']::text[]),
  ('Garlic', 'pantry', array['1 garlic clove','½ garlic clove','3 garlic cloves minced','4 garlic cloves','finely chopped garlic','frozen chopped garlic','garlic','minced garlic','One clove']::text[]),
  ('Carrot', 'fridge', array['1 large carrot','2 to 3 carrots cut into 1 inch pieces','3 carrots','carrots','diced carrot','peeled and diced carrot']::text[]),
  ('Onion', 'pantry', array['1 large onion','1 large onion chopped','1 medium onion','1 onion','1 small onion','1 yellow onion diced','1-1.5 medium size onion','2 large onions','2 medium onions','chopped onion','finely chopped white onion','onion','yellow onion']::text[]),
  ('Fresh basil', 'fridge', array['1 large stem fresh basil sprig','fresh basil']::text[]),
  ('Tomato', 'fridge', array['1 medium size tomato','1 Tomato','chopped tomato','chopped tomato (see note)','finely chopped tomato']::text[]),
  ('Green chile', 'fridge', array['1 mild green chile','2 mild green chiles','2 mild to medium-hot green chiles']::text[]),
  ('Parmigiano-Reggiano cheese', 'fridge', array['1 ounce Parmigiano-Reggiano cheese','fresh grated Parmesan cheese','parmesan cheese']::text[]),
  ('Red onion', 'pantry', array['1 red onion','2 large red onions','finely chopped red onion']::text[]),
  ('Puff pastry', 'freezer', array['1 sheet puff pastry','PASTRY']::text[]),
  ('Chicken thigh', 'fridge', array['1.25 - 1.5 kg/ 2.5 - 3 lb skinless boneless chicken thighs OR breast']::text[]),
  ('Half and half', 'fridge', array['½ to 1 cup half and half']::text[]),
  ('Baking powder', 'pantry', array['1⁄4 tsp baking powder','baking powder']::text[]),
  ('Sun-dried tomatoes', 'pantry', array['12 sun-dried tomatoes in oil','roughly chopped sun dried tomatoes']::text[]),
  ('Fire roasted tomatoes', 'pantry', array['14 ounces fire roasted tomatoes']::text[]),
  ('Goat''s cheese', 'fridge', array['1x150g of soft goat’s cheese']::text[]),
  ('Crushed tomatoes', 'pantry', array['2  cans crushed tomatoes','canned crushed tomato','crushed tomatoes']::text[]),
  ('Dried red chile', 'pantry', array['2 dried red chiles']::text[]),
  ('Cream cheese', 'fridge', array['2 heaped tbsp cream cheese']::text[]),
  ('Broccoli', 'fridge', array['2 packed cups broccoli']::text[]),
  ('Pepper (bell)', 'fridge', array['2 peppers','4 large romano peppers']::text[]),
  ('Chicken breast', 'fridge', array['2 pounds chicken (skinless and boneless','4  skinless and boneless chicken breasts (640g total)','8 boneless','boneless','Some kind of cooked chicken/meat']::text[]),
  ('Olive oil', 'pantry', array['2 tbl olive oil','extra virgin olive oil','extra-virgin olive oil','olive oil']::text[]),
  ('Thyme', 'pantry', array['2 thyme sprigs or 1½ tsp dried','dried thyme','few thyme sprigs']::text[]),
  ('Whole cloves', 'pantry', array['2 whole cloves']::text[]),
  ('Haricot beans', 'pantry', array['2 x 400g cans haricot beans']::text[]),
  ('Banana', 'pantry', array['2-3 bananas']::text[]),
  ('Green lentils', 'pantry', array['2x 400g tins of green lentils']::text[]),
  ('Chickpeas', 'pantry', array['3  cans of chickpeas OR 12 oz/340g (1 1/2 cups) dried chickpeas']::text[]),
  ('Red-skinned potato', 'pantry', array['3 - 4 red-skinned potatoes cut into 1 inch pieces']::text[]),
  ('Cashews', 'pantry', array['3-4 cashew nuts','cashews']::text[]),
  ('Chicken leg', 'fridge', array['4 lbs/1.8kg 14 count Chicken Legs or drumsticks','6 to 8 pieces drumstick']::text[]),
  ('White beans (cannellini)', 'pantry', array['4x420g  cans white beans (cannellini beans)']::text[]),
  ('Curry leaves', 'fridge', array['6 to 8 curry leaves']::text[]),
  ('Chapati', 'pantry', array['8 small plain chapatis']::text[]),
  ('Pasta', 'pantry', array['8oz/225g pasta (you can use whole wheat','pasta or crusty bread']::text[]),
  ('Salt', 'pantry', array['A pinch of salt','kosher salt','salt','salt (Note 3)','salt and pepper','sea salt','Salt']::text[]),
  ('Saffron', 'pantry', array['a pinch saffron or tumeric']::text[]),
  ('All-purpose flour', 'pantry', array['all-purpose flour','flour','roasted gram flour']::text[]),
  ('Almond milk', 'fridge', array['almond milk']::text[]),
  ('Beetroot powder', 'pantry', array['Any other mix-ins such as beetroot powder']::text[]),
  ('Asafoetida', 'pantry', array['asafetida','Asafoetida']::text[]),
  ('Baby spinach', 'fridge', array['baby spinach','fresh spinach','spinach leaves']::text[]),
  ('Cauliflower', 'fridge', array['bag frozen cauliflower florets','cauliflower florets','potatoes or diced button mushrooms or cauliflower']::text[]),
  ('Berries', 'freezer', array['Berries']::text[]),
  ('Black mustard seeds', 'pantry', array['black mustard seeds','black mustard seeds (rai)','Mustard Seeds']::text[]),
  ('Black pepper', 'pantry', array['Black pepper','black pepper','fresh ground black pepper','freshly ground black pepper','ground black pepper','pepper']::text[]),
  ('Water', 'pantry', array['boiling water (for cooking)','of water','Water','water']::text[]),
  ('Bread', 'pantry', array['Bread','Lingongrova Brown Bread','One slice of bread']::text[]),
  ('Brown sugar', 'pantry', array['brown sugar','dark brown sugar or jaggery powder','light brown sugar']::text[]),
  ('Buckwheat flakes', 'pantry', array['Buckwheat flakes']::text[]),
  ('Canned chopped tomatoes', 'pantry', array['can chopped tomatoes']::text[]),
  ('Chili powder', 'pantry', array['Cayenne or Red Chili powder','chili powder','Chilli powder','Indian red chili powder or paprika','Kashmiri chilli powder','red chili powder','red chili powder or paprika']::text[]),
  ('Cheese', 'fridge', array['Cheese','Grated Cheese','shredded sharp cheddar cheese']::text[]),
  ('Chicken tikka', 'fridge', array['Chicken Tikka']::text[]),
  ('Chinese cooking wine', 'pantry', array['Chinese cooking wine or dry sherry (key ingredient']::text[]),
  ('Chocolate chips', 'pantry', array['chocolate chips']::text[]),
  ('Fresh cilantro', 'fridge', array['chopped fresh cilantro','cilantro (fresh','Cilantro leaves','fresh cilantro leaves']::text[]),
  ('Fresh fenugreek leaves', 'fridge', array['chopped fresh fenugreek leaves']::text[]),
  ('Fresh parsley', 'fridge', array['chopped fresh flat-leaf parsley','chopped fresh parsley optional','chopped parsley','finely chopped parsley','fresh parsley','parsley','small bunch parsley']::text[]),
  ('Fresh ginger', 'fridge', array['chopped fresh ginger','fresh ginger','freshly minced or grated ginger','ginger','Ginger','grated fresh ginger','grated ginger','minced ginger']::text[]),
  ('Shallot', 'pantry', array['finely chopped shallots']::text[]),
  ('Cider vinegar', 'pantry', array['cider vinegar']::text[]),
  ('Cocoa powder', 'pantry', array['cocoa powder']::text[]),
  ('Coconut oil', 'pantry', array['coconut oil','coconut oil or neutral cooking oil']::text[]),
  ('Cooking oil', 'pantry', array['cooking oil','oil','Oil','sunflower oil','vegetable oil','flavourless oil/melted butter','of neutral oil/butter','rapeseed oil or butter']::text[]),
  ('Cornflakes', 'pantry', array['Cornflakes']::text[]),
  ('Cornstarch', 'pantry', array['cornflour','cornflour/cornstarch','cornstarch']::text[]),
  ('Cottage cheese', 'fridge', array['cottage cheese (I used 4% milkfat)']::text[]),
  ('Peanut butter', 'pantry', array['Creamy Peanut Butter','peanut butter','peanut butter can use any nut or seed butter of choice']::text[]),
  ('Crushed red pepper flakes', 'pantry', array['crushed red pepper flakes']::text[]),
  ('Paneer', 'fridge', array['cubed paneer','paneer']::text[]),
  ('Curry sauce', 'pantry', array['Curry Sauce']::text[]),
  ('Yogurt', 'fridge', array['dahi (curd) or plain Greek yogurt','low-fat natural yogurt','plain yoghurt','plain yogurt','thick plain yoghurt','Yoghurt','YOGHURT RANCH SAUCE :']::text[]),
  ('Dried basil', 'pantry', array['dried basil']::text[]),
  ('Dried black-eyed peas', 'pantry', array['dried black-eyed peas (lobia)']::text[]),
  ('Dried fenugreek leaves', 'pantry', array['dried fenugreek leaves','dried fenugreek leaves (kasuri methi)','kasoori methi']::text[]),
  ('Dried oregano', 'pantry', array['dried oregano']::text[]),
  ('Dried red kidney beans', 'pantry', array['dried red kidney beans (rajma; see note)']::text[]),
  ('Split pigeon peas', 'pantry', array['dried split pigeon peas (toor dal)']::text[]),
  ('Yellow moong beans', 'pantry', array['dried yellow moong beans']::text[]),
  ('Dill', 'pantry', array['EACH dried dill']::text[]),
  ('Mushroom ketchup', 'pantry', array['each tomato purée and mushroom ketchup/Worcestershire sauce']::text[]),
  ('Mustard oil', 'pantry', array['edible mustard oil','mustard oil']::text[]),
  ('Fajita seasoning', 'pantry', array['fajita seasoning']::text[]),
  ('Oat flour', 'pantry', array['oat flour','rolled oats/oat flour']::text[]),
  ('Garam masala', 'pantry', array['garam masala','Garam masala']::text[]),
  ('Garlic powder', 'pantry', array['garlic powder']::text[]),
  ('Ghee', 'pantry', array['ghee']::text[]),
  ('Ginger garlic paste', 'fridge', array['ginger and garlic paste','Ginger garlic paste']::text[]),
  ('Granulated sugar', 'pantry', array['granulated sugar','sugar','of sugar/sweetener or half a banana']::text[]),
  ('Spring onion', 'fridge', array['Green onion']::text[]),
  ('Green peas', 'freezer', array['Frozen Peas','frozen peas','Green Peas','green peas']::text[]),
  ('Ground fennel seeds', 'pantry', array['ground fennel seeds']::text[]),
  ('Ground flaxseed', 'pantry', array['ground flaxseed']::text[]),
  ('Ground goat meat', 'fridge', array['ground goat meat/lamb/turkey']::text[]),
  ('Turmeric', 'pantry', array['Ground Turmeric','ground turmeric','turmeric']::text[]),
  ('Honey', 'pantry', array['honey','of honey']::text[]),
  ('Italian herbs', 'pantry', array['Italian dried herbs','Italian Seasoning','Italian seasoning/Oregano']::text[]),
  ('Lemon juice', 'fridge', array['fresh lemon juice','lemon juice','lemon juice from 1 large lemon','Squeeze of lemon juice','white distilled vinegar or lemon juice']::text[]),
  ('Lemon wedges', 'fridge', array['lemon wedges']::text[]),
  ('Light cream', 'fridge', array['light cream','light cream (or cashew cream or coconut milk']::text[]),
  ('Mango chutney', 'pantry', array['mango chutney']::text[]),
  ('Maple syrup', 'pantry', array['maple syrup','maple syrup can substitute agave nectar']::text[]),
  ('Medium curry powder', 'pantry', array['medium curry powder']::text[]),
  ('Milk', 'fridge', array['milk','Milk - lactose free','of milk']::text[]),
  ('Mint sauce', 'fridge', array['mint sauce from a jar']::text[]),
  ('Nigella seeds', 'pantry', array['nigella seeds','nigella seeds or substitute with cumin or fennel seeds']::text[]),
  ('Nutmeg', 'pantry', array['nutmeg']::text[]),
  ('Oats', 'pantry', array['of oats','Rolled oats gluten free','whole oats']::text[]),
  ('Onion powder', 'pantry', array['onion powder']::text[]),
  ('Panko breadcrumbs', 'pantry', array['panko bread crumbs','panko breadcrumbs']::text[]),
  ('Paprika', 'pantry', array['paprika','smoked paprika']::text[]),
  ('Dijon mustard', 'fridge', array['dijon mustard']::text[]),
  ('Bottle gourd', 'fridge', array['peeled and diced bottle gourd (calabash)']::text[]),
  ('Potato', 'pantry', array['peeled and diced potato','potatoes','sweet potatoes']::text[]),
  ('Pizza dough', 'freezer', array['Pizza dough (family size']::text[]),
  ('Pizza sauce', 'pantry', array['Pizza sauce']::text[]),
  ('Sambar masala', 'pantry', array['sambar masala (optional; see note)']::text[]),
  ('Sesame oil', 'pantry', array['sesame oil']::text[]),
  ('Sesame seeds', 'pantry', array['Sesame seeds']::text[]),
  ('Shredded mozzarella', 'fridge', array['shredded mozzarella']::text[]),
  ('Soy sauce', 'pantry', array['soy sauce']::text[]),
  ('Steamed vegetables', 'fridge', array['Steamed veggies']::text[]),
  ('Tamarind paste', 'pantry', array['tamarind paste']::text[]),
  ('Thick coconut milk', 'pantry', array['thick coconut milk']::text[]),
  ('Tomato paste', 'pantry', array['tomato paste','tomato puree']::text[]),
  ('Tomato sauce', 'pantry', array['tomato sauce','TOMATO BASIL SAUCE']::text[]),
  ('Vanilla extract', 'pantry', array['Vanilla','vanilla','vanilla extract']::text[]),
  ('Vinegar', 'pantry', array['vinegar any kind']::text[]),
  ('Whole wheat flour', 'pantry', array['Whole Wheat Flour']::text[]),
  ('Worcestershire sauce', 'pantry', array['Worcestershire sauce']::text[]),
  ('UNCLEAR', 'pantry', array['2x to make double and freeze half for another day','BULK PREP: x 6','FILLING','GARNISHES :','HONEY SOY MARINADE SAUCE:','MARINADE 1','MARINADE 2','MICROWAVE VERSION','OVEN VERSION','Rågfras','SERVES 2','SERVING SAUCE:','TEMPERING']::text[]),
  ('Cumin seeds', 'pantry', array['Cumin seeds','cumin seeds','whole cumin seeds']::text[]),
  ('Ground cumin', 'pantry', array['cumin','ground cumin','Jeera/Cumin powder']::text[]),
  ('Green cardamom pods', 'pantry', array['6 green cardamom pods']::text[]),
  ('Ground green cardamom', 'pantry', array['ground green cardamom']::text[]),
  ('Coriander powder', 'pantry', array['Corainder powder','coriander','Coriander powder','ground coriander']::text[]),
  ('Fresh coriander', 'fridge', array['small bunch coriander']::text[]),
  ('Shallot', 'pantry', array['chopped shallots or onion']::text[]),
  ('Vegetable stock', 'pantry', array['vegetable broth','vegetable broth or water','vegetable or chicken stock']::text[]),
  ('Beef stock', 'pantry', array['beef or chicken broth']::text[]),
  ('Butter', 'fridge', array['butter','unsalted butter']::text[]),
  ('Stewing beef', 'fridge', array['beef chuck','diced stewing beef','stew beef frozen or fresh']::text[]),
  ('Beef mince', 'fridge', array['lean mince beef']::text[]);

update recipe_ingredients ri set master_ingredient_id = mi.id
from master_ingredients mi
where ri.master_ingredient_id is null and trim(ri.name) = any(mi.aliases);

update recipe_variant_ingredients rvi set master_ingredient_id = mi.id
from master_ingredients mi
where rvi.master_ingredient_id is null and trim(rvi.name) = any(mi.aliases);